[package]
name = "client_socket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trprot = { path = "../trprot" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
iced = "0.10.*"
