[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.*", features = ["csr"] }
strum = "0.25"
strum_macros = "0.25"
serde = "1"
serde_derive = "1"
gloo = "0.9"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlInputElement"]
