[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.20.*", features = ["csr"] }
wasm-bindgen-futures = "0.4.*"
reqwasm = "0.5.*"
serde = "1"
serde_derive = "1"
js-sys = "0.3"


[dependencies.web-sys]
version = "0.3"
features = ["HtmlInputElement"]
